[book]
authors = ["Bacchus"]
language = "ko"
multilingual = false
src = "src"
title = "SNUCSE GPU 서비스 매뉴얼"

[preprocessor.gettext]
after = ["links"]

[build]
extra-watch-dirs = ["po"]

[output.html]
additional-css = ["theme/language-picker.css"]
